pipeline {
    agent { docker { image 'maven:3.3.3' } 
          }
    stages {
	    
        stage('build') {
            steps {
               git url: 'https://github.com/vekatkriish/javaenv.git'
                sh "mvn clean package"
                sh "cd target && ls -al"           
            }
        }
    }
}