pipeline {
    agent { docker { image 'maven:3.3.3' } 
          }
    stages {
	    
        stage('build') {
            steps {
                sh "git clone https://github.com/vekatkriish/javaenv.git"
                sh "cd javaenv"
                sh "mvn clean package | cd target"
                sh "ls -al"           
            }
        }
    }
}